#include <adwaita.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#include "arrow.h"
#include "shape.h"

static void arrow_draw_one(Shape* self, cairo_t* cr, double scale, RGBA color, double dx_off, double dy_off) {
    double length = points_distance(&self->points[0], &self->points[1]);
    double angle = points_angle(&self->points[0], &self->points[1]);

    const double head_length      = 28.0 * scale;
    const double head_tick_height = 10.0 * scale;
    const double head_tick_length = 3.0 * scale;
    const double tail_height      = 16.0 * scale;

    cairo_save(cr);
    cairo_set_line_width(cr, 5.0);
    cairo_set_line_cap(cr, CAIRO_LINE_CAP_ROUND);
    cairo_set_line_join(cr, CAIRO_LINE_JOIN_MITER);
    cairo_set_source_rgba(cr, color.r, color.g, color.b, color.a);

    // Move origin to start point, rotate so +X points at the end 
    cairo_translate(cr, self->points[0].x + dx_off, self->points[0].y + dy_off);
    cairo_rotate(cr, angle);

    // Now draw a purely horizontal arrow from (0,0) to (length, 0)
    cairo_move_to(cr, 0, 0);
    cairo_line_to(cr, length - head_length, -tail_height / 2);
    cairo_line_to(cr, length - head_length - head_tick_length, -tail_height / 2 - head_tick_height);
    cairo_line_to(cr, length, 0);
    cairo_line_to(cr, length - head_length - head_tick_length, tail_height / 2 + head_tick_height);
    cairo_line_to(cr, length - head_length, tail_height / 2);
    cairo_line_to(cr, 0, 0);

    cairo_fill_preserve(cr);
    cairo_stroke(cr);

    cairo_restore(cr);
}

static void arrow_draw(Shape* self, cairo_t* cr, double scale) {
    // Drop shadow, then the colored arrow on top
    arrow_draw_one(self, cr, scale, self->color_shadow, 1, 1);
    arrow_draw_one(self, cr, scale, self->color, 0, 0);

    if(self->is_showing_handles) {
        shape_draw_handle_at(self, self->points[0], cr, scale);
        shape_draw_handle_at(self, self->points[1], cr, scale);
    }
}

static bool arrow_is_hit(Shape* self, double x, double y) {
    // Not checking the real shape of the arrow.
    // I will check on both side of the vector
    // generated by the shape point 0 to point 1

    double threshold = 10.0; // how much distance on each side of the vector

    double dx = self->points[1].x - self->points[0].x;
    double dy = self->points[1].y - self->points[0].y;
    double len_sq = dx * dx + dy * dy;

    double t = 0.0;
    if (len_sq != 0.0) {
        t = ((x - self->points[0].x) * dx + (y - self->points[0].y) * dy) / len_sq;
        t = CLAMP (t, 0.0, 1.0);
    }

    double closest_x = self->points[0].x + t * dx;
    double closest_y = self->points[0].y + t * dy;

    double dist_x = x - closest_x;
    double dist_y = y - closest_y;

    return (dist_x * dist_x + dist_y * dist_y) <= threshold * threshold;
}

static bool arrow_is_handle_hit(Shape* self, double x, double y) {
    double threshold = 10.0; // how much distance on each side of the vector

    for(int i = 0; i < 2; i++) {
        double dx = self->points[i].x - x;
        double dy = self->points[i].y - y;
        double len_sq = dx*dx + dy*dy;

        if(len_sq <= threshold*threshold) {
            self->dragging_point_index = 1;
            return true;
        }
    }
    return false;
}

Shape *arrow_new(Point start, Point end) {
    Shape* self = shape_new();
    if(!self) {
        return NULL;
    }

    self->type = SHAPE_TYPE_ARROW;
    self->draw = arrow_draw;
    self->is_hit = arrow_is_hit;
    self->is_handle_hit = arrow_is_handle_hit;
    self->points[0] = start;
    self->points[1] = end;

    self->color = (RGBA){ 0.8784, 0.0157, 0.749, 1};
    self->color_shadow = (RGBA){ 0.1, 0.1, 0.1, 0.3};

    return self;
}